### ISSUE TITLE
Can't install through NPM - configure error

### ISSUE THREAD

**Issue by CameronHamidi** [Karumi/learnyougit#6]
I'm using Node.js 8.11.1, npm 5.6.0. Here is the output when I enter `install learnyougit -g` in the Windows 10 terminal:

```
`npm WARN deprecated colors-tmpl@0.1.1: no longer maintained
npm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.
C:\Users\Username\AppData\Roaming\npm\learnyougit -> C:\Users\Username\AppData\Roaming\npm\node_modules\learnyougit\learnyougit.js

> nodegit@0.16.0 install C:\Users\Username\AppData\Roaming\npm\node_modules\learnyougit\node_modules\nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Running install script
node-pre-gyp
ERR! Tried to download(403): https://nodegit.s3.amazonaws.com/nodegit/nodegit/nodegit-v0.16.0-node-v57-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for nodegit@0.16.0 and node@8.11.1 (node-v57 ABI, unknown) (falling back to source compile with node-gyp)
gyp
ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\Username\Anaconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Username\\AppData\\Roaming\\npm\\node_modules\\learnyougit\\node_modules\\nodegit\\build\\Release\\nodegit.node" "--module_name=nodegit" "--module_path=C:\\Users\\Username\\AppData\\Roaming\\npm\\node_modules\\learnyougit\\node_modules\\nodegit\\build\\Release"
gyp ERR! cwd C:\Users\Username\AppData\Roaming\npm\node_modules\learnyougit\node_modules\nodegit
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp
ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Username\AppData\Roaming\npm\node_modules\learnyougit\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\Username\AppData\Roaming\npm\node_modules\learnyougit\node_modules\nodegit\build\Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Username\AppData\Roaming\npm\node_modules\learnyougit\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp
ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Username\\AppData\\Roaming\\npm\\node_modules\\learnyougit\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Username\AppData\Roaming\npm\node_modules\learnyougit\node_modules\nodegit\build\Release\nodegit.node --module_name=nodegit --module_path=C:\Users\Username\AppData\Roaming\npm\node_modules\learnyougit\node_modules\nodegit\build\Release' (1)
ERR! cwd C:\Users\Username\AppData\Roaming\npm\node_modules\learnyougit\node_modules\nodegit
node-pre-gyp ERR! node -v v8.11.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodegit@0.16.0 install: `node lifecycleScripts/preinstall && node lifecycleScripts/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodegit@0.16.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Username\AppData\Roaming\npm-cache\_logs\2018-05-11T04_46_54_257Z-debug.log`
```

I've tried a fresh install of Node.js, didn't help

**Comment by Serchinastico** [comment]
Hi @CameronHamidi,

Sorry for the late response. The issue isn't in this repository but when installing one of the dependencies it uses. The error you are seeing is that you don't have Python configured, try installing it in your machine and setting the PYTHON environment variable so that it can be used by other processes.
